# Generated by Django 3.0.7 on 2020-09-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='games',
            field=models.CharField(choices=[('League of Legends', 'League of Legends'), ('PubG', 'PubG'), ('DOTA 2', 'DOTA 2'), ('Valorant', 'Valorant'), ('Call Of Duty', 'Call Of Duty'), ('Arena of Valor', 'Arena of Valor'), ('Free Fire', 'Free Fire'), ('Clash Royale', 'Clash Royale')], max_length=200, null=True),
        ),
    ]
