# Generated by Django 3.0.7 on 2020-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200902_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='games',
        ),
        migrations.AddField(
            model_name='member',
            name='games',
            field=models.ManyToManyField(to='accounts.Games'),
        ),
    ]
