# Generated by Django 3.0.7 on 2020-11-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lead'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMembers',
            new_name='Winners',
        ),
        migrations.RenameField(
            model_name='winners',
            old_name='team',
            new_name='winner',
        ),
        migrations.RemoveField(
            model_name='winners',
            name='member',
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(to='accounts.Member'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(to='accounts.Team'),
        ),
        migrations.AddField(
            model_name='winners',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Tournament'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
