# Generated by Django 3.0.7 on 2020-11-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tournament_is_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
