# Generated by Django 3.0.7 on 2020-09-08 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200902_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='games',
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tierlist', models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3')], max_length=200, null=True)),
                ('game', models.ManyToManyField(to='accounts.Game')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
        ),
    ]
