# Generated by Django 3.0.7 on 2020-09-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200908_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='game',
        ),
        migrations.AddField(
            model_name='tier',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Game'),
        ),
    ]
