# Generated by Django 3.0.7 on 2020-09-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200914_0834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
        migrations.AlterField(
            model_name='member',
            name='college',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='UserMember',
        ),
    ]
