# Generated by Django 3.0.7 on 2020-10-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
